import './globals.css'
import { Roboto, VT323 } from 'next/font/google'

const vt323 = VT323({ subsets: ['latin'], variable: '--font-VT323', weight: ['400'] })

const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto', weight: ['400', '700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${vt323.variable} ${roboto.variable} font-roboto`}>{children}</body>
    </html>
  )
}
